### ISSUE TITLE
[BUG] Weird address template/layout on last step of checkout

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#48] opened 2022-08-16 13:16 UTC
**To Reproduce**
1. Add product to cart and go to checkout
2. Use below address details.
3. Go to next step of checkout

Name: John Doe
Postcode: 1012JS
House number: 1
Country: The Netherlands
Phone: +31612345678

**Expected result**
I am expecting the template/layout on the last step of checkout to reflect what I filled in (there are 2 blocks with the address) So I would expect something like this:

John Doe
Dam 1
1012JS Amsterdam
Nederland
T: +31612345678

**Actual result**
John Doe
Dam 1 90
1012JS Amsterdam
Nederland
T: +31612345678
tig_housenumber
1
tig_housenumber_addition

tig_street
Dam

PS: Notice the extra '90' in the street field. This comes from an older address I filled in (I think).

**Workaround**
None (yet)

**Screenshots**
![Afrekenen (4)](https://user-images.githubusercontent.com/197229/184888455-8829709a-c1c3-445c-814a-b35e9010b99e.png)

** Please complete the following information**
- Magento version: Magento 2.4.3-p2
- PHP version: 7.4

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-16 14:20
Hi @Aquive ,

We cannot reproduce this issue on a clean Magento 2.4.3-p2 with the extension.  Is it possible you have more extensions active? Is there a One step checkout active? Or is this a certain kind of PSP? 

Have a great day,
Jeffrey

**Comment by Aquive** [comment] 2022-08-16 14:23
@tig-jeffreybranderhorst thanks for your reply :)

This is the native checkout. The PSP module is from Mollie (https://github.com/mollie/magento2). And yes, there are several more modules active. But I don't know if any of those are interacting with the checkout.

I will try to isolate the issue first. Thanks again!

**Comment by Aquive** [comment] 2022-08-17 13:35
@tig-jeffreybranderhorst so I have been testing this on another clean installation of Magento 2.4.3-p2 with sample data. Below is the result. To exclude it is some sort of browser caching issue I confirmed on another browser which I normally don't use. Same result.

![Checkout](https://user-images.githubusercontent.com/197229/185147445-34f775ae-c40f-4c88-ac92-9519e6453807.png)

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-18 07:22
Hi @Aquive ,

I also tested this in a new browser I normally don't use. But I still cannot reproduce this issue. 
![image](https://user-images.githubusercontent.com/23314965/185334256-aa503eaa-49ec-47b9-83a5-c36f573baf80.png)

Is it possible you contact us at support@tig.nl ? So we can maybe test on your test environment to figure out the differences/issue. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-12-19 12:13
Hi @Aquive ,

We will close this issue because we were not able to reproduce it. If needed you can always contact us at support@tig.nl

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-12-19 12:13 UTC
