### ISSUE TITLE
[BUG] Address housenumber missing in shipping address section

### ISSUE THREAD

**Issue by albsa** [tig-nl/postcode-magento2#24] opened 2021-01-26 11:56 UTC
Lastest plugin version: 1.3.1
Magento 2.3.3

**To Reproduce**
We have not been able to reproduce the issue yet, still this issue is a pattern and happend since the latest update from version 1.2.x to 1.3.1

**Expected result**
Housenumber in both the shipping address section and billing address section.

**Actual result**
The shipping address has no house number in some cases.
The billing address has the housenumber, but somehow the shipping address is empty, only the street.

We thought maybe because it merged all on streetline 1, now we have the house number and addition on streetline 2 and still the issue occurs.

**Workaround**
None

**Screenshots**

** Please complete the following information**
- Magento version: 2.3.3

**Comment by Paulsky** [comment] 2021-01-29 11:16
Did you find a fix for this issue? I believe we have the same problem on Magento 2.4 and Amasty Checkout

**Comment by tig-jeffreybranderhorst** [comment] 2021-01-29 11:32
Hi @albsa and @Paulsky  ,

Do the orders also have no house number in the backend?  Because in the next version of PostNL we are going to release, there is gonna be a fix that fixes the house numbers in the front end. If the orders don't have a house number in the backend then we will need to investigate this further, can you then contact us at support@tig.nl

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2021-01-29 12:22
Hi @albsa  and @Paulsky ,

I was too fast with my answer, this is about Postcodeservice we don't have seen these errors before there. We would like to investigate it and help you further, could you still contact us at support@tig.nl

Have a great day,
Jeffrey

**Comment by albsa** [comment] 2021-01-29 13:12
Hi @tig-jeffreybranderhorst ,

I already sent an e-mail regarding this issue.
Ticket: (SPS-73) 

Did not get any reply yet.

There is no pattern whichfor I can relate the issue to.
However, like explained, billing address always contains the full address.
Shipping address is missing the housenumber in 20% of the cases.

I tried many different thing but my test orders did not see this issue.
Hopefully you guys can find out a quick fix for this issue as it causes a lot manual extra work.

**Comment by tig-jeffreybranderhorst** [comment] 2021-01-29 13:22
Hi @albsa ,

I see the issue, that is weird because we answered your issue on 26 January. Just have sent our message again we hope you will receive this one, if not we will have to mail directly. 

Have a great day,
Jeffrey

**Comment by albsa** [comment] 2021-01-29 14:28
@tig-jeffreybranderhorst did not receive anything.
Could you provide me your e-mail, will send you a direct e-mail instead.

**Comment by tig-jeffreybranderhorst** [comment] 2021-02-01 11:31
Hi @albsa 

You have already found me and we will support you further thank you for contacting

**Comment by Paulsky** [comment] 2021-02-01 12:51
We do have have orders with no house number in the backend. We are now switching checkouts. Maybe this will solve the issue. I will keep you posted. Thank you

**Comment by albsa** [comment] 2021-02-26 08:33
Hi @Paulsky did you find a solution for this issue?

**Comment by Paulsky** [comment] 2021-02-26 08:48
@albsa Unfortunately not. We have switched checkouts, but that didn't seem to fix the issue. After almost a month still no solution. Time is running out, so I'm not sure if we can keep using this extension.

Our issue is that the housenumber is missing in the billing section, but it is available in the shipping section.

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-03 13:40
Hi @Paulsky ,

Could you also email us at support@tig.nl so we also assist you further! 

Have a great day,
Jeffrey

**Comment by Paulsky** [comment] 2021-03-04 10:09
Hello @tig-jeffreybranderhorst,

We are already in conversation (SD-22747). Thanks.

Kind regards,
Paul Wijnberg

**Comment by albsa** [comment] 2021-03-25 11:50
@Paulsky @tig-jeffreybranderhorst has this issue been debugged already?

**Comment by tig-jeffreybranderhorst** [comment] 2021-03-25 12:58
Hi @albsa ,

In the upcoming version of the extension the fix will be added!

Have a great day,
Jeffrey

**Comment by Paulsky** [comment] 2021-04-02 14:59
@tig-jeffreybranderhorst when will the next version be released?

**Comment by tig-jeffreybranderhorst** [comment] 2021-04-06 13:50
Hey @Paulsky ,

We are in the testing phase, If we find nothing we will be releasing the next sprint. Our sprints are 2 weeks, we started with this sprint this week. 

Have a great day,
Jeffrey

**Comment by Paulsky** [comment] 2021-04-07 06:57
Hello @tig-jeffreybranderhorst ,

Alright, thank you very much. Have a great day!

**Comment by albsa** [comment] 2021-04-15 18:22
@tig-jeffreybranderhorst is the release already done yet? It's getting a daily job now to fix the housenumbers.

**Comment by tig-jeffreybranderhorst** [comment] 2021-04-16 10:03
Hi @albsa ,

The release has been planned for the next sprint, our next sprint will begin next week.

Have a great day,
Jeffrey

**Comment by albsa** [comment] 2021-04-30 08:58
@tig-jeffreybranderhorst we're having trouble now since the latest updates with orders from foreign countries, like Germany.
The orders are missing the whole housenumber, as well in the shipping and billing section.

Please check this out ASAP, it's getting problematic these bugs and very time consuming.

**Comment by tig-jeffreybranderhorst** [comment] 2021-05-03 07:46
Hi @albsa ,

Thank you for submitting this, we will investigate this thoroughly. To have fast and more directer contact could you also mail us at support@tig.nl about this? 

Have a great day,
Jeffrey

**Comment by Skullsneeze** [comment] 2022-01-11 12:52
Just to hop onto this issue as well. We're seeing the same issue. Verified that by turning off the TIG_Postcode module the issue no longer occurs. We are running the latest version (1.4.1).

I'm going to do some debugging and if I manage to find the root cause I will share my findings here

**Comment by Skullsneeze** [comment] 2022-01-11 13:41
Reverting the changes made to the following files [in this commit](https://github.com/tig-nl/postcode-magento2/commit/c62c07b67fbe9f605ea99734cf747410ee81e40f ) seem to resolve the issue (to some extent).

- view/frontend/web/js/action/set-billing-address-mixin.js
- view/frontend/web/js/action/set-shipping-information-mixin.js

After reverting these files the house number is preserved. It does still look like the addition is stripped though. At with this our checkout process is no longer blocked for now.

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-12 07:59
Hi @Skullsneeze,

Thank you for the info! We are refactoring the code, so I will tell our developers your findings. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-12 08:13
Hi @Skullsneeze,

I spoke to one of our developers and this is one of the fixes that the refactor will solve. 

Have a great day,
Jeffrey

**Comment by wimvdputten** [comment] 2022-01-27 14:58
Is there any news regarding this issue?
It seems that reverting the commit suggested by Skullsneeze does fix the missing house number in not NL countries.
But it still leaves us with a problem, when a user fills in a house number from the Netherlands, and then switches to another country.

Both house numbers get merged together into the street field instead of using just one.

**Comment by tig-jeffreybranderhorst** [comment] 2022-01-28 14:15
Hi @wimvdputten,

The update I can give is, that we are still working hard on the refactor. We will also test your issue in the refactor! Thank you for submitting.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-07-15 13:33
Hi all,

The newest version of the extension should have fixed this issue. 

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-07-15 13:33 UTC
