### ISSUE TITLE
[BUG] House number disappears from shipping info after changing billing address

### ISSUE THREAD

**Issue by glevhen** [tig-nl/postcode-magento2#14] opened 2020-01-15 16:24 UTC
Magento 2.3.2
Theme: Magento/luma
tig/postcode-magento2: 1.2.4
Checkout usage: Two Step Checkout Luma
House number field: Street address line 1

On the shipping step fill address details via success postcode autocomplete and go to the payments step
the house number available in the shipping info 
![image](https://user-images.githubusercontent.com/16398798/72450502-2826c000-37c3-11ea-8879-0ac1b9714707.png)
select payment method and change billing address by another valid postcode and house number and house number disappears from shipping address info
![image](https://user-images.githubusercontent.com/16398798/72450763-8d7ab100-37c3-11ea-918e-8b9584fad952.png)

**Comment by tig-jaspersmits** [comment] 2020-01-23 08:48
Hi @glevhen ,

Thanks for submitting this. Unfortunate to hear that this happens. I've just tested this but I can't reproduce this. Can you maybe share a screenshot or video on how this happens? Maybe I'm testing it the wrong way.

Kind regards,

Jasper
TIG

**Comment by glevhen** [comment] 2020-01-28 16:10
@tig-jaspersmits Hello, sorry for delay, I recorded screen for custom theme, but you also can reproduce it for magento themes such as Magento/luma or Magento/blank, hope it will help you to reproduce the issue
![jzPEcYHHio](https://user-images.githubusercontent.com/16398798/73281857-45af4d00-41f9-11ea-8724-14acaaf9e457.gif)

**Comment by tig-jaspersmits** [comment] 2020-01-30 08:36
Hi @glevhen ,

Thanks for providing us the steps to follow. My colleague and I both tried to reproduce this, but were unsuccessful in doing so. Are you using any other extensions which could impact the checkout process or address details? Is it possible to test with other extensions disabled and just the postcode service enabled?

Looking forward to your response.

Kind regards,
Jasper
TIG

**Comment by GuidoHub** [comment] 2020-03-02 11:55
@glevhen @tig-jaspersmits 

This seems to be done by script /Magento_Checkout/js/model/shipping-rates-validator.min.js. I was debugging something else where shipping address housenumber is changed to billing addres housenumber. Did you check this also. So my shipping housenumber is 13 and billing 15, when I look at the backend it's both 15.

**Comment by tig-jaspersmits** [comment] 2020-03-02 13:45
Hi @GuidoHub ,

There should be something on our backlog that will fix this. Expect it in an upcoming release.

Kind regards,
Jasper
TIG

**Comment by GuidoHub** [comment] 2020-03-03 10:44
Hi @tig-jaspersmits 

Any idear when we could expect this update? Or is there some how we can already see the fix in a commit?

**Comment by tig-jaspersmits** [comment] 2020-03-03 11:03
@GuidoHub ,

No information about the release yet. But you can keep an eye on the release notes here: https://docs.tig.nl/x/B4FaAg

I brought it under the attention of the developers again a few minutes ago.

Kind regards,
Jasper

**Comment by tig-jaspersmits** [comment] 2020-03-23 08:25
Hi @GuidoHub ,

It seems that this has been fixed in Magento version 2.3.4. Is it possible to update to that version and check if the problem persists?

Kind regards,
Jasper

**Closed** 2020-04-14 06:18 UTC
Labels: on backlog
