### ISSUE TITLE
[BUG] Missing / unused translations

### ISSUE THREAD

**Issue by basvanpoppel** [tig-nl/postcode-magento2#47] opened 2022-08-16 07:13 UTC
**To Reproduce**
1. Go to checkout, country NL, with locale nl_NL
2. Fill in a non-existing postcode/housenr combination

**Expected result**

1. A Dutch error message (as present in the translation file in your module)
2. A Dutch label for the house number addition field

**Actual result**
Message and field label are English. (looking at the module I noticed 'house number', 'housenumber', 'house number addition' and 'housenumber addition' being used random. 

**Workaround**

1. I've created a patch for the error message making it translatable in view/base/web/js/postcode-handler/postcode-nl.js
2. Add translations in theme

**Screenshots**

** Please complete the following information**
- Magento version: 2.4.3-p2
- PHP version: 7.4

**Comment by Aquive** [comment] 2022-08-16 12:35
I can confirm some translations are not working. Like this one:

`Sorry, we could not find the address on the given zip code and house number combination. If you are sure that the zip code and house number are correct, please fill in the address details manually.`

**Comment by tig-jeffreybranderhorst** [comment] 2022-08-16 14:14
Hi @basvanpoppel and @Aquive ,

We have created a backlog item for this, it seems since the last version the translations are not being called anymore. They still exist so we will make a fix that the translations are used again.

Thank you for submitting this issue.

Have a great day,
Jeffrey

**Comment by jeroen-dhm** [comment] 2022-09-14 09:52
Any progress on this? I'm currently running into the same problem, which is actually stalling the release of a shop right now.

**Comment by tig-jeffreybranderhorst** [comment] 2022-09-15 12:01
Hi @jeroen-dhm ,

I know this issue have been picked up, and it ready for testing and after that it will be released.
An eta i cannot give yet.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment] 2022-12-19 15:07
Hi @jeroen-dhm ,

We just released a new version, and we fixed this issue in that version. 
If you still got question after updating the extension, don't hesitate to contact us at support@tig.nl

Have a great day,
Jeffrey

**Closed by tig-jeffreybranderhorst** 2022-12-19 15:07 UTC
Labels: on backlog
